# Generated by Django 4.0.5 on 2022-08-06 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=20)),
                ('dev_code', models.CharField(max_length=3)),
                ('url_to_intercept', models.CharField(max_length=50, null=True)),
                ('url_to_intercept_new_response_code', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=7)),
                ('url', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=2000)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.testingsession')),
            ],
        ),
    ]
