# Generated by Django 4.0.5 on 2022-07-25 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tappearances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startmilliseconds', models.IntegerField(db_column='startMilliseconds')),
                ('endmilliseconds', models.IntegerField(db_column='endMilliseconds')),
            ],
            options={
                'db_table': 'TAppearances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tcharacters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('imageurl', models.CharField(blank=True, db_column='imageUrl', max_length=500, null=True)),
            ],
            options={
                'db_table': 'TCharacters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tclips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('videourl', models.CharField(blank=True, db_column='videoUrl', max_length=500, null=True)),
            ],
            options={
                'db_table': 'TClips',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=20)),
                ('dev_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TestingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=7)),
                ('url', models.CharField(max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpsons_app.testingsession')),
            ],
        ),
    ]
