# Generated by Django 4.0.5 on 2022-07-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpsons_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingsession',
            name='url_to_intercept',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testingsession',
            name='url_to_intercept_new_response_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
